spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/radiostack
    username: radiostack
    password: radiostack
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.radiostack: DEBUG

