/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gameclients;

import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import java.sql.*;
import db.*;
import static db.User.getUserRoleByUsername;
import static db.Game.addGame;
import java.io.File;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author User
 */

public class AddEmpresa extends javax.swing.JFrame implements Observer {

    private String username;
    private String role;
    private File selectedFile;
    
    // Declaración de las variables booleanas para indicar si los campos han sido clicados
    private boolean gameNameFieldFirstClick = true;
    private boolean descriptionFieldFirstClick = true;
    private boolean dateFieldFirstClick=true;
    
    /**
     * Creates new form Login
     * @param username
     */
    public AddEmpresa(String username, String role) {
        this.username = username;
        this.role = role;
        initComponents();
        
        // Establecer el nombre de usuario en el JTextField
        jTextField1.setText(username);
        
        this.setLocationRelativeTo(null);
        
        // Suscribirse a GlobalState
        GlobalState.getInstance().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        CompanyNameField = new javax.swing.JTextField();
        BotonPanel = new javax.swing.JPanel();
        Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Logo2_BG = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        UserLabel1 = new javax.swing.JLabel();
        DateField = new javax.swing.JTextField();
        UserLabel5 = new javax.swing.JLabel();
        DescriptionField = new javax.swing.JTextField();
        UserLabel7 = new javax.swing.JLabel();
        BotonPanel1 = new javax.swing.JPanel();
        Button1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocationByPlatform(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(26, 41, 58));
        BG.setForeground(new java.awt.Color(23, 29, 39));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("ADD COMPANY");
        BG.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 210, 30));

        UserLabel.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setText("COMPANY NAME: ");
        BG.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        CompanyNameField.setBackground(new java.awt.Color(255, 255, 255));
        CompanyNameField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CompanyNameField.setForeground(new java.awt.Color(204, 204, 204));
        CompanyNameField.setText(" Ingrese el nombre de la empresa");
        CompanyNameField.setBorder(null);
        CompanyNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CompanyNameFieldMousePressed(evt);
            }
        });
        CompanyNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyNameFieldActionPerformed(evt);
            }
        });
        BG.add(CompanyNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 210, 30));

        BotonPanel.setBackground(new java.awt.Color(23, 29, 37));
        BotonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Button.setBackground(new java.awt.Color(23, 29, 37));
        Button.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Button.setForeground(new java.awt.Color(255, 255, 255));
        Button.setText("GO BACK");
        Button.setBorder(null);
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanelLayout = new javax.swing.GroupLayout(BotonPanel);
        BotonPanel.setLayout(BotonPanelLayout);
        BotonPanelLayout.setHorizontalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanelLayout.setVerticalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(BotonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 120, 50));

        jPanel1.setBackground(new java.awt.Color(23, 29, 37));

        Logo2_BG.setBackground(new java.awt.Color(255, 255, 255));
        Logo2_BG.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Logo2_BG.setForeground(new java.awt.Color(0, 0, 0));
        Logo2_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/steam.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(Logo2_BG)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(240, 240, 240))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo2_BG, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        BG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 110));

        UserLabel1.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel1.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel1.setText("DEPARTURE DATE: ");
        BG.add(UserLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        DateField.setBackground(new java.awt.Color(255, 255, 255));
        DateField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DateField.setForeground(new java.awt.Color(204, 204, 204));
        DateField.setText(" Ingrese la fecha de creacion");
        DateField.setBorder(null);
        DateField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DateFieldMousePressed(evt);
            }
        });
        DateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateFieldActionPerformed(evt);
            }
        });
        BG.add(DateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 210, 30));

        UserLabel5.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel5.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel5.setText("DESCRIPTION: ");
        BG.add(UserLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        DescriptionField.setBackground(new java.awt.Color(255, 255, 255));
        DescriptionField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DescriptionField.setForeground(new java.awt.Color(204, 204, 204));
        DescriptionField.setText(" Ingrese la descripcion de la empresa");
        DescriptionField.setBorder(null);
        DescriptionField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DescriptionFieldMousePressed(evt);
            }
        });
        DescriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionFieldActionPerformed(evt);
            }
        });
        BG.add(DescriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 210, 30));

        UserLabel7.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel7.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel7.setText("IMAGE: ");
        BG.add(UserLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 190, -1));

        BotonPanel1.setBackground(new java.awt.Color(92, 126, 16));
        BotonPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Button1.setBackground(new java.awt.Color(92, 126, 16));
        Button1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Button1.setForeground(new java.awt.Color(255, 255, 255));
        Button1.setText("ADD");
        Button1.setBorder(null);
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanel1Layout = new javax.swing.GroupLayout(BotonPanel1);
        BotonPanel1.setLayout(BotonPanel1Layout);
        BotonPanel1Layout.setHorizontalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanel1Layout.setVerticalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(BotonPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 120, 50));

        jButton1.setText("Archivos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BG.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        role=User.getUserRoleByUsername(username);
        LoggedMenu steam3 = new LoggedMenu(username, role);
        steam3.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
        steam3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // Obtén los valores de los campos
        String name = CompanyNameField.getText();
        String departure_date = DateField.getText();
        String description = DescriptionField.getText();
        Blob logo = null;
        
        // Validaciones
        if (name.trim().isEmpty() || departure_date.trim().isEmpty() || description.trim().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que la fecha esté en el formato correcto (asumamos yyyy-MM-dd)
        if (!departure_date.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "La fecha debe estar en el formato yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que se haya seleccionado una imagen
        if (selectedFile == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una imagen.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Convertir el archivo seleccionado en un Blob
        if (selectedFile != null) {
            try {
                byte[] fileContent = Files.readAllBytes(selectedFile.toPath());
                logo = new javax.sql.rowset.serial.SerialBlob(fileContent);  // Usa SerialBlob para crear el Blob
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al convertir la imagen en Blob: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    
        try {
            // Llama al método addGame de la clase UserDB
            Empresa.registrarEmpresa(name, description, departure_date, logo);

            // Muestra un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Empresa añadida correctamente", "Empresa añadida", JOptionPane.INFORMATION_MESSAGE);

            // Regresa a la ventana principal
            DownloadGame steam4 = new DownloadGame(username,role);
            SelectCompany selectCompany = new SelectCompany(username,role);
            selectCompany.onNewCompanyAdded(name);
            steam4.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
            steam4.setVisible(true);

            // Cierra la ventana actual
            this.dispose();
        
        } catch (HeadlessException e) {
            // Manejo de errores relacionados con la interfaz gráfica (JOptionPane)
            System.err.println("Error de interfaz gráfica: " + e.getMessage());
        } catch (Exception e) {
            // Manejo general de cualquier otra excepción
            JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Esto imprime el stack trace en la consola para facilitar la depuración
        }

    }//GEN-LAST:event_Button1ActionPerformed
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar una imagen");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png", "gif"));

        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();  // Almacena el archivo seleccionado en la variable de clase
            System.out.println("Archivo seleccionado: " + selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFieldActionPerformed

    private void DateFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateFieldMousePressed
        if (dateFieldFirstClick) {
            DateField.setText("");
            DateField.setForeground(Color.black);
            dateFieldFirstClick=false;
        }
    }//GEN-LAST:event_DateFieldMousePressed

    private void DescriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionFieldActionPerformed

    }//GEN-LAST:event_DescriptionFieldActionPerformed

    private void DescriptionFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescriptionFieldMousePressed
        // Si es la primera vez que se hace clic en el campo
        if (descriptionFieldFirstClick) {
            DescriptionField.setText("");  // Borra el texto
            DescriptionField.setForeground(Color.black);  // Cambia el color del texto
            descriptionFieldFirstClick = false;  // Cambia el estado a falso para que no se vuelva a ejecutar esta acción
        }
        // El campo funcionará normalmente después de la primera vez
    }//GEN-LAST:event_DescriptionFieldMousePressed

    private void CompanyNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyNameFieldActionPerformed

    private void CompanyNameFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompanyNameFieldMousePressed
        // Si es la primera vez que se hace clic en el campo
        if (gameNameFieldFirstClick) {
            CompanyNameField.setText("");  // Borra el texto
            CompanyNameField.setForeground(Color.black);  // Cambia el color del texto
            gameNameFieldFirstClick = false;  // Cambia el estado a falso para que no se vuelva a ejecutar esta acción
        }
        // El campo funcionará normalmente después de la primera vez
    }//GEN-LAST:event_CompanyNameFieldMousePressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BotonPanel;
    private javax.swing.JPanel BotonPanel1;
    private javax.swing.JButton Button;
    private javax.swing.JButton Button1;
    private javax.swing.JTextField CompanyNameField;
    private javax.swing.JTextField DateField;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JLabel Logo2_BG;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel UserLabel1;
    private javax.swing.JLabel UserLabel5;
    private javax.swing.JLabel UserLabel7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String empresaSeleccionada, ImageIcon empresaLogo) {
        jLabel1.setForeground(Color.WHITE); // Aquí se cambia el color del texto a blanco
        jLabel1.setText(empresaSeleccionada);
        Logo2_BG.setIcon(empresaLogo);
    }
}
