/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gameclients;

import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import java.sql.*;
import db.*;
import static db.User.getUserRoleByUsername;
import static db.Game.addGame;
import java.io.File;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/**
 *
 * @author User
 */
public class AddGame extends javax.swing.JFrame implements Observer{

    private String username;
    private String role;
    private File selectedFile;
    
    // Declaración de las variables booleanas para indicar si los campos han sido clicados
    private boolean gameNameFieldFirstClick = true;
    private boolean priceFieldFirstClick = true;
    private boolean descriptionFieldFirstClick = true;
    private boolean continentFieldFirstClick = true;
    private boolean numberUnitsFieldFirstClick = true;
    private boolean dateFieldFirstClick=true;
    
    /**
     * Creates new form Login
     * @param username
     */
    public AddGame(String username) {
        this.username = username;
        initComponents();
        
        // Establecer el nombre de usuario en el JTextField
        jTextField1.setText(username);
        
        this.setLocationRelativeTo(null);
        
        // Suscribirse a GlobalState
        GlobalState.getInstance().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        GameNameField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        BotonPanel = new javax.swing.JPanel();
        Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Logo2_BG = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        UserLabel1 = new javax.swing.JLabel();
        DateField = new javax.swing.JTextField();
        UserLabel2 = new javax.swing.JLabel();
        UserLabel3 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        UserLabel4 = new javax.swing.JLabel();
        UserLabel5 = new javax.swing.JLabel();
        DescriptionField = new javax.swing.JTextField();
        UserLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        UserLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        numberUnitsField = new javax.swing.JTextField();
        continentField = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        BotonPanel1 = new javax.swing.JPanel();
        Button1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        UserLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocationByPlatform(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(26, 41, 58));
        BG.setForeground(new java.awt.Color(23, 29, 39));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("ADD NEW GAME");
        BG.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 210, 30));

        UserLabel.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setText("NAME: ");
        BG.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        GameNameField.setBackground(new java.awt.Color(255, 255, 255));
        GameNameField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        GameNameField.setForeground(new java.awt.Color(204, 204, 204));
        GameNameField.setText(" Ingrese el nombre del juego");
        GameNameField.setBorder(null);
        GameNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GameNameFieldMousePressed(evt);
            }
        });
        GameNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameNameFieldActionPerformed(evt);
            }
        });
        BG.add(GameNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 210, 30));

        PasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("PEGGY");
        BG.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        BotonPanel.setBackground(new java.awt.Color(23, 29, 37));
        BotonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Button.setBackground(new java.awt.Color(23, 29, 37));
        Button.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Button.setForeground(new java.awt.Color(255, 255, 255));
        Button.setText("GO BACK");
        Button.setBorder(null);
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanelLayout = new javax.swing.GroupLayout(BotonPanel);
        BotonPanel.setLayout(BotonPanelLayout);
        BotonPanelLayout.setHorizontalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanelLayout.setVerticalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(BotonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 120, 50));

        jPanel1.setBackground(new java.awt.Color(23, 29, 37));

        Logo2_BG.setBackground(new java.awt.Color(255, 255, 255));
        Logo2_BG.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Logo2_BG.setForeground(new java.awt.Color(0, 0, 0));
        Logo2_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/steam.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(Logo2_BG)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(240, 240, 240))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo2_BG, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        BG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 110));

        UserLabel1.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel1.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel1.setText("DEPARTURE DATE: ");
        BG.add(UserLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        DateField.setBackground(new java.awt.Color(255, 255, 255));
        DateField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DateField.setForeground(new java.awt.Color(204, 204, 204));
        DateField.setText(" Ingrese la fecha de salida");
        DateField.setBorder(null);
        DateField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DateFieldMousePressed(evt);
            }
        });
        DateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateFieldActionPerformed(evt);
            }
        });
        BG.add(DateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 210, 30));

        UserLabel2.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel2.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel2.setText("CATEGORY: ");
        BG.add(UserLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        UserLabel3.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel3.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel3.setText("CONTINENT: ");
        BG.add(UserLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        priceField.setBackground(new java.awt.Color(255, 255, 255));
        priceField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        priceField.setForeground(new java.awt.Color(204, 204, 204));
        priceField.setText(" Ingrese un precio de venta");
        priceField.setBorder(null);
        priceField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                priceFieldMousePressed(evt);
            }
        });
        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });
        BG.add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 210, 30));

        UserLabel4.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel4.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel4.setText("Nº UNITS: ");
        BG.add(UserLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        UserLabel5.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel5.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel5.setText("DESCRIPTION: ");
        BG.add(UserLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        DescriptionField.setBackground(new java.awt.Color(255, 255, 255));
        DescriptionField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DescriptionField.setForeground(new java.awt.Color(204, 204, 204));
        DescriptionField.setText(" Ingrese una descripcion para el juego");
        DescriptionField.setBorder(null);
        DescriptionField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DescriptionFieldMousePressed(evt);
            }
        });
        DescriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionFieldActionPerformed(evt);
            }
        });
        BG.add(DescriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 210, 30));

        UserLabel6.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel6.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel6.setText("PRICE: ");
        BG.add(UserLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(204, 204, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<seleccionar>", "Accion", "Aventura", "FPS", "RPG", "Survival", "Survival Horror", "Terror", "Estrategia", "RTS", "Puzzle", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        BG.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 210, 30));

        UserLabel7.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel7.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel7.setText("IMAGE: ");
        BG.add(UserLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 190, -1));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(204, 204, 204));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<seleccionar>", "PC", "PS4", "PS5", "Switch", "Xbox One", " " }));
        BG.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 210, 30));

        numberUnitsField.setBackground(new java.awt.Color(255, 255, 255));
        numberUnitsField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        numberUnitsField.setForeground(new java.awt.Color(204, 204, 204));
        numberUnitsField.setText(" Ingrese el numero de unidades");
        numberUnitsField.setBorder(null);
        numberUnitsField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                numberUnitsFieldMousePressed(evt);
            }
        });
        numberUnitsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberUnitsFieldActionPerformed(evt);
            }
        });
        BG.add(numberUnitsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 210, 30));

        continentField.setBackground(new java.awt.Color(255, 255, 255));
        continentField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        continentField.setForeground(new java.awt.Color(204, 204, 204));
        continentField.setText(" Ingrese el nombre del continente");
        continentField.setBorder(null);
        continentField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                continentFieldMousePressed(evt);
            }
        });
        continentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continentFieldActionPerformed(evt);
            }
        });
        BG.add(continentField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 210, 30));

        jComboBox3.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(204, 204, 204));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<seleccionar>", "PEGI 3", "PEGI 7", "PEGI 12", "PEGI 16", "PEGI 18", " " }));
        BG.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 210, 30));

        BotonPanel1.setBackground(new java.awt.Color(92, 126, 16));
        BotonPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Button1.setBackground(new java.awt.Color(92, 126, 16));
        Button1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Button1.setForeground(new java.awt.Color(255, 255, 255));
        Button1.setText("ADD");
        Button1.setBorder(null);
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanel1Layout = new javax.swing.GroupLayout(BotonPanel1);
        BotonPanel1.setLayout(BotonPanel1Layout);
        BotonPanel1Layout.setHorizontalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanel1Layout.setVerticalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(BotonPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 120, 50));

        jButton1.setText("Archivos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BG.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 200, 30));

        UserLabel8.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel8.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel8.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel8.setText("PLATFORM: ");
        BG.add(UserLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GameNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GameNameFieldActionPerformed

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        role=User.getUserRoleByUsername(username);
        LoggedMenu steam3 = new LoggedMenu(username, role);
        steam3.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
        steam3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonActionPerformed

    private void GameNameFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GameNameFieldMousePressed
        // Si es la primera vez que se hace clic en el campo
        if (gameNameFieldFirstClick) {
            GameNameField.setText("");  // Borra el texto
            GameNameField.setForeground(Color.black);  // Cambia el color del texto
            gameNameFieldFirstClick = false;  // Cambia el estado a falso para que no se vuelva a ejecutar esta acción
        }
        // El campo funcionará normalmente después de la primera vez
    }//GEN-LAST:event_GameNameFieldMousePressed

    private void priceFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priceFieldMousePressed
        // Si es la primera vez que se hace clic en el campo
        if (priceFieldFirstClick) {
            priceField.setText("");  // Borra el texto
            priceField.setForeground(Color.black);  // Cambia el color del texto
            priceFieldFirstClick = false;  // Cambia el estado a falso para que no se vuelva a ejecutar esta acción
        }
        // El campo funcionará normalmente después de la primera vez
    }//GEN-LAST:event_priceFieldMousePressed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void DescriptionFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescriptionFieldMousePressed
        // Si es la primera vez que se hace clic en el campo
        if (descriptionFieldFirstClick) {
            DescriptionField.setText("");  // Borra el texto
            DescriptionField.setForeground(Color.black);  // Cambia el color del texto
            descriptionFieldFirstClick = false;  // Cambia el estado a falso para que no se vuelva a ejecutar esta acción
        }
        // El campo funcionará normalmente después de la primera vez
    }//GEN-LAST:event_DescriptionFieldMousePressed

    private void DescriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionFieldActionPerformed
        
    }//GEN-LAST:event_DescriptionFieldActionPerformed

    private void numberUnitsFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberUnitsFieldMousePressed
        // Si es la primera vez que se hace clic en el campo
        if (numberUnitsFieldFirstClick) {
            numberUnitsField.setText("");  // Borra el texto
            numberUnitsField.setForeground(Color.black);  // Cambia el color del texto
            numberUnitsFieldFirstClick = false;  // Cambia el estado a falso para que no se vuelva a ejecutar esta acción
        }
        // El campo funcionará normalmente después de la primera vez
    }//GEN-LAST:event_numberUnitsFieldMousePressed

    private void numberUnitsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberUnitsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberUnitsFieldActionPerformed

    private void continentFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continentFieldMousePressed
        // Si es la primera vez que se hace clic en el campo
        if (continentFieldFirstClick) {
            continentField.setText("");  // Borra el texto
            continentField.setForeground(Color.black);  // Cambia el color del texto
            continentFieldFirstClick = false;  // Cambia el estado a falso para que no se vuelva a ejecutar esta acción
        }
        // El campo funcionará normalmente después de la primera vez
    }//GEN-LAST:event_continentFieldMousePressed

    private void continentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continentFieldActionPerformed

    }//GEN-LAST:event_continentFieldActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // Obtén los valores de los campos
        String name = GameNameField.getText();
        String departure_date = DateField.getText();
        String category = (String) jComboBox1.getSelectedItem();
        String continent = (String) jComboBox2.getSelectedItem();
        String description = DescriptionField.getText();
        String price = priceField.getText();
        String units = numberUnitsField.getText();
        String platform = (String) jComboBox2.getSelectedItem();
        String peggy = (String) jComboBox3.getSelectedItem();
        Blob image = null;
        
        // Validaciones
        if (name.trim().isEmpty() || departure_date.trim().isEmpty() || category == null || continent == null || description.trim().isEmpty() 
                || price.trim().isEmpty() || units.trim().isEmpty() || platform == null || peggy == null) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar si el campo de precio es un número válido
        try {
            Double.parseDouble(price);  // Si esto lanza una excepción, no es un número válido
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar si las unidades son un número entero válido
        try {
            Integer.parseInt(units);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Las unidades deben ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que la fecha esté en el formato correcto (asumamos yyyy-MM-dd)
        if (!departure_date.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "La fecha debe estar en el formato yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que se haya seleccionado una imagen
        if (selectedFile == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una imagen.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Convertir el archivo seleccionado en un Blob
        if (selectedFile != null) {
            try {
                byte[] fileContent = Files.readAllBytes(selectedFile.toPath());
                image = new javax.sql.rowset.serial.SerialBlob(fileContent);  // Usa SerialBlob para crear el Blob
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al convertir la imagen en Blob: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    
        try {
            // Llama al método addGame de la clase UserDB
            Game.addGame(name, departure_date, category, continent, description, price, units, platform, peggy, username,image);

            // Muestra un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Juego añadido correctamente", "Juego añadido", JOptionPane.INFORMATION_MESSAGE);

            // Regresa a la ventana principal
            DownloadGame steam4 = new DownloadGame(username,role);
            steam4.onNewGameAdded(name);
            steam4.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
            steam4.setVisible(true);

            // Cierra la ventana actual
            this.dispose();
        
        } catch (HeadlessException e) {
            // Manejo de errores relacionados con la interfaz gráfica (JOptionPane)
            System.err.println("Error de interfaz gráfica: " + e.getMessage());
        } catch (Exception e) {
            // Manejo general de cualquier otra excepción
            JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Esto imprime el stack trace en la consola para facilitar la depuración
        }

    }//GEN-LAST:event_Button1ActionPerformed
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar una imagen");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png", "gif"));

        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();  // Almacena el archivo seleccionado en la variable de clase
            System.out.println("Archivo seleccionado: " + selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFieldActionPerformed

    private void DateFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateFieldMousePressed
        if (dateFieldFirstClick) {
            DateField.setText("");
            DateField.setForeground(Color.black);
            dateFieldFirstClick=false;
        }
    }//GEN-LAST:event_DateFieldMousePressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BotonPanel;
    private javax.swing.JPanel BotonPanel1;
    private javax.swing.JButton Button;
    private javax.swing.JButton Button1;
    private javax.swing.JTextField DateField;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JTextField GameNameField;
    private javax.swing.JLabel Logo2_BG;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel UserLabel1;
    private javax.swing.JLabel UserLabel2;
    private javax.swing.JLabel UserLabel3;
    private javax.swing.JLabel UserLabel4;
    private javax.swing.JLabel UserLabel5;
    private javax.swing.JLabel UserLabel6;
    private javax.swing.JLabel UserLabel7;
    private javax.swing.JLabel UserLabel8;
    private javax.swing.JTextField continentField;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField numberUnitsField;
    private javax.swing.JTextField priceField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String empresaSeleccionada, ImageIcon empresaLogo) {
        jLabel1.setForeground(Color.WHITE); // Aquí se cambia el color del texto a blanco
        jLabel1.setText(empresaSeleccionada);
        jLabel1.setIcon(empresaLogo);
    }
}
