/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gameclients;

import static db.Descarga.eliminarDescargas;
import db.User;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import static db.User.getUserRoleByUsername;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.ImageIcon;


/**
 * Clase Descargas que representa la interfaz gráfica para visualizar el historial de descargas de un usuario.
 * Extiende de JFrame para utilizar las funcionalidades de una ventana en Java Swing.
 * @author User
 */
public class Descargas extends javax.swing.JFrame implements Observer {

    // Atributos de la clase Descargas
    private String username;
    private String role;
    
    /**
     * Constructor de la clase Descargas. Inicializa la interfaz gráfica y carga el historial de descargas.
     * 
     * @param username Nombre de usuario que inicia la sesión en la aplicación
     */   
    public Descargas(String username) {
        this.username = username;
        initComponents();// Inicializa los componentes gráficos de la interfaz
        
        // Establecer el nombre de usuario en el JTextField
        jTextField1.setText(username);
        
        // Suscribirse a GlobalState
        GlobalState.getInstance().addObserver(this);
        
        this.setLocationRelativeTo(null);// Centra la ventana en la pantalla
        historyArea.setEditable(false); // Deshabilita la edición del área de texto donde se muestra el historial
        loadDownloadHistory(); // Carga el historial de descargas desde un archivo de texto
    }
    
     /**
     * Método que carga el historial de descargas desde un archivo de texto y lo muestra en el área de texto.
     */
    private void loadDownloadHistory() {
        historyArea.setText(""); // Limpiar el área de texto antes de cargar
        try (BufferedReader reader = new BufferedReader(new FileReader("download_history.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                historyArea.append(line + "\n");
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar el historial: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        BotonPanel = new javax.swing.JPanel();
        Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Logo2_BG = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyArea = new javax.swing.JTextArea();
        BotonPanel1 = new javax.swing.JPanel();
        Button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocationByPlatform(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(26, 41, 58));
        BG.setForeground(new java.awt.Color(23, 29, 39));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonPanel.setBackground(new java.awt.Color(23, 29, 37));
        BotonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Button.setBackground(new java.awt.Color(23, 29, 37));
        Button.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Button.setForeground(new java.awt.Color(255, 255, 255));
        Button.setText("GO BACK");
        Button.setBorder(null);
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanelLayout = new javax.swing.GroupLayout(BotonPanel);
        BotonPanel.setLayout(BotonPanelLayout);
        BotonPanelLayout.setHorizontalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanelLayout.setVerticalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(BotonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 120, 50));

        jPanel1.setBackground(new java.awt.Color(23, 29, 37));

        Logo2_BG.setBackground(new java.awt.Color(255, 255, 255));
        Logo2_BG.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Logo2_BG.setForeground(new java.awt.Color(0, 0, 0));
        Logo2_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/steam.png"))); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Logo2_BG)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo2_BG, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        historyArea.setColumns(20);
        historyArea.setRows(5);
        jScrollPane1.setViewportView(historyArea);

        BG.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 560, 350));

        BotonPanel1.setBackground(new java.awt.Color(23, 29, 37));
        BotonPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Button1.setBackground(new java.awt.Color(23, 29, 37));
        Button1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Button1.setForeground(new java.awt.Color(255, 255, 255));
        Button1.setText("CLEAN");
        Button1.setBorder(null);
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanel1Layout = new javax.swing.GroupLayout(BotonPanel1);
        BotonPanel1.setLayout(BotonPanel1Layout);
        BotonPanel1Layout.setHorizontalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanel1Layout.setVerticalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(BotonPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * Acción que se ejecuta cuando se hace clic en el botón "Go Back".
     * Cierra la ventana actual y abre la interfaz del menú principal.
     * 
     * @param evt Evento que desencadena la acción
     */

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        role=User.getUserRoleByUsername(username);
        LoggedMenu steam3 = new LoggedMenu(username,role);
        steam3.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
        steam3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonActionPerformed
    
    /**
     * Acción que se ejecuta cuando se interactúa con el campo de texto del nombre de usuario.
     * 
     * @param evt Evento que desencadena la acción
     */
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // Confirmación antes de borrar el historial
        int response = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres borrar el historial?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            // Limpiar el archivo de historial
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("download_history.txt"))) {
                writer.write(""); // Esto asegura que el archivo está vacío
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al borrar el historial: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            
            
            // Limpiar el área de texto de historial
            historyArea.setText("");
            try{
                eliminarDescargas();
            }catch(Exception e){
                // Registrar el error para saber qué ocurre
                e.printStackTrace(); // Imprime la traza del error en la consola
                // O puedes mostrar un mensaje informativo
                System.out.println("Error al eliminar descargas: " + e.getMessage());
            }
            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, "El historial ha sido borrado con éxito.");
        }
    }//GEN-LAST:event_Button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BotonPanel;
    private javax.swing.JPanel BotonPanel1;
    private javax.swing.JButton Button;
    private javax.swing.JButton Button1;
    private javax.swing.JLabel Logo2_BG;
    private javax.swing.JTextArea historyArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String empresaSeleccionada, ImageIcon empresaLogo) {
        jLabel1.setForeground(Color.WHITE); // Aquí se cambia el color del texto a blanco
        jLabel1.setText(empresaSeleccionada);
        Logo2_BG.setIcon(empresaLogo);
    }
}
