/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gameclients;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import com.mycompany.gameclients.AddGame;
import java.io.BufferedWriter;
import java.io.FileWriter;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import java.sql.*;
import javax.swing.JOptionPane;

import db.*;
import static db.User.getUserIdByNameAndSurname;
import static db.User.updateUser;
import java.awt.Color;

/**
 *
 * @author User
 */
public class GestionarPerfil extends javax.swing.JFrame implements Observer {

    public String username; // Variable para almacenar el nombre de usuario
    private String userRole; // Variable para almacenar el rol del usuario
    
    private boolean nameFirstClick = true;
    private boolean lastNameFirstClick = true;
    private boolean userDNIFirstClick = true;
    private boolean phoneNumberFirstClick = true;
    private boolean userEmailFirstClick = true;
    private boolean passwordFieldFirstClick = true;
    private boolean passwordFieldRepeatFirstClick = true;


       
    /**
     * Creates new form Steam
     */
    public GestionarPerfil(String username) {
        this.username = username; // Almacenar el nombre de usuario
        initComponents();
        
        // Establecer el nombre de usuario en el JTextField
        jTextField1.setText(username);
        
        // Suscribirse a GlobalState
        GlobalState.getInstance().addObserver(this);
        
        // Evitar que la ventana sea redimensionable
        setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        loadUserData();      
    }
    
    // Método para cargar los datos del usuario
    private void loadUserData() {
        // Aquí debes implementar la lógica para cargar los datos del usuario desde la base de datos
        // y establecerlos en los campos de texto. Por ejemplo:
        
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/juegos", "root", "");
             PreparedStatement stmt = conn.prepareStatement("SELECT * FROM users WHERE username = ?")) {
            
            stmt.setString(1, username);
            ResultSet rs = stmt.executeQuery();
            
            if (rs.next()) {
                jTextFieldNombre.setText(rs.getString("nombre"));
                jTextFieldApellido.setText(rs.getString("apellido"));
                jTextFieldDNI.setText(rs.getString("dni"));
                jTextFieldPhoneNumber.setText(rs.getString("phoneNumber"));
                jTextFieldEmail.setText(rs.getString("email"));
                jPasswordField.setText(rs.getString("password"));
                jPasswordRepeatField.setText(rs.getString("password"));
                userRole = rs.getString("role");
                jComboBoxRole.setSelectedItem(userRole); // Seleccionas ese valor en el combo box
                
                // Llamar al método para ajustar la interfaz según el rol
                adjustUIForRole(userRole);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar los datos del usuario.");
        }
    }

    
    // Método para ajustar la interfaz según el rol del usuario
    private void adjustUIForRole(String role) {
        if ("admin".equalsIgnoreCase(role)) {
            // Mostrar todos los componentes si es administrador
            jComboBoxRole.setEnabled(true);
        } else {
            // Deshabilitar componentes si no es administrador
            jComboBoxRole.setEnabled(false);
        }
    }
    
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BotonPanel = new javax.swing.JPanel();
        Button = new javax.swing.JButton();
        UserLabel = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JTextField();
        UserLabel1 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        UserLabel2 = new javax.swing.JLabel();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        UserLabel3 = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        UserLabel5 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        UserLabel6 = new javax.swing.JLabel();
        UserLabel7 = new javax.swing.JLabel();
        BotonPanel1 = new javax.swing.JPanel();
        reloadButton = new javax.swing.JButton();
        jComboBoxRole = new javax.swing.JComboBox<>();
        UserLabel4 = new javax.swing.JLabel();
        jPasswordRepeatField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(27, 40, 56));

        jPanel1.setBackground(new java.awt.Color(26, 41, 58));

        jPanel2.setBackground(new java.awt.Color(23, 29, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/steam.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BotonPanel.setBackground(new java.awt.Color(23, 29, 37));
        BotonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Button.setBackground(new java.awt.Color(23, 29, 37));
        Button.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Button.setForeground(new java.awt.Color(255, 255, 255));
        Button.setText("GO BACK");
        Button.setBorder(null);
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanelLayout = new javax.swing.GroupLayout(BotonPanel);
        BotonPanel.setLayout(BotonPanelLayout);
        BotonPanelLayout.setHorizontalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanelLayout.setVerticalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserLabel.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setText("NAME: ");

        jTextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldNombreMousePressed(evt);
            }
        });
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField.setBorder(null);
        jPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFieldMousePressed(evt);
            }
        });
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        UserLabel1.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel1.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel1.setText("CONTRASEÑA: ");

        jTextFieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldEmail.setBorder(null);
        jTextFieldEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldEmailMousePressed(evt);
            }
        });
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        UserLabel2.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel2.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel2.setText("EMAIL: ");

        jTextFieldPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPhoneNumber.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextFieldPhoneNumber.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPhoneNumber.setBorder(null);
        jTextFieldPhoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldPhoneNumberMousePressed(evt);
            }
        });
        jTextFieldPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneNumberActionPerformed(evt);
            }
        });

        UserLabel3.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel3.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel3.setText("PHONE NUMBER: ");

        jTextFieldDNI.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDNI.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextFieldDNI.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldDNI.setBorder(null);
        jTextFieldDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldDNIMousePressed(evt);
            }
        });
        jTextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIActionPerformed(evt);
            }
        });

        UserLabel5.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel5.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel5.setText("DNI: ");

        jTextFieldApellido.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldApellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextFieldApellido.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldApellido.setBorder(null);
        jTextFieldApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldApellidoMousePressed(evt);
            }
        });
        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });

        UserLabel6.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel6.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel6.setText("LASTNAME: ");

        UserLabel7.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel7.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel7.setText("ROL: ");

        BotonPanel1.setBackground(new java.awt.Color(92, 126, 16));
        BotonPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        reloadButton.setBackground(new java.awt.Color(92, 126, 16));
        reloadButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        reloadButton.setForeground(new java.awt.Color(255, 255, 255));
        reloadButton.setText("UPDATE");
        reloadButton.setBorder(null);
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanel1Layout = new javax.swing.GroupLayout(BotonPanel1);
        BotonPanel1.setLayout(BotonPanel1Layout);
        BotonPanel1Layout.setHorizontalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(reloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanel1Layout.setVerticalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(reloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jComboBoxRole.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxRole.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jComboBoxRole.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<seleccionar>", "Admin", "User" }));
        jComboBoxRole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBoxRoleMousePressed(evt);
            }
        });
        jComboBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRoleActionPerformed(evt);
            }
        });

        UserLabel4.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel4.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel4.setText("REPEAT PASSWORD: ");

        jPasswordRepeatField.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordRepeatField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPasswordRepeatField.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordRepeatField.setBorder(null);
        jPasswordRepeatField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordRepeatFieldMousePressed(evt);
            }
        });
        jPasswordRepeatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordRepeatFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserLabel2)
                    .addComponent(UserLabel3)
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserLabel)
                    .addComponent(UserLabel7)
                    .addComponent(jComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserLabel4)
                    .addComponent(jPasswordRepeatField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserLabel6)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserLabel5)
                    .addComponent(UserLabel1)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(BotonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(UserLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(UserLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(UserLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(UserLabel2)
                                .addGap(5, 5, 5)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserLabel3)
                            .addComponent(UserLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(UserLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(UserLabel4)
                                .addGap(0, 0, 0)
                                .addComponent(jPasswordRepeatField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(23, 29, 37));
        jMenuBar1.setForeground(new java.awt.Color(23, 29, 37));
        jMenuBar1.setMargin(new java.awt.Insets(0, 0, 10, 0));
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        LoggedMenu steam3 = new LoggedMenu(username,userRole);
        steam3.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
        steam3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonActionPerformed

    private void jTextFieldNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNombreMousePressed
        if (nameFirstClick) {
            jTextFieldNombre.setForeground(Color.black);
            nameFirstClick = false;
        }
    }//GEN-LAST:event_jTextFieldNombreMousePressed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed

    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jPasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMousePressed
        if (passwordFieldFirstClick) {
            jPasswordField.setForeground(Color.black);
            passwordFieldFirstClick = false;
            }
    }//GEN-LAST:event_jPasswordFieldMousePressed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jTextFieldEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEmailMousePressed
        if (userEmailFirstClick) {
            jTextFieldEmail.setForeground(Color.black);
            userEmailFirstClick = false;
        }
    }//GEN-LAST:event_jTextFieldEmailMousePressed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldPhoneNumberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNumberMousePressed
        if (phoneNumberFirstClick) {
            jTextFieldPhoneNumber.setForeground(Color.black);
            phoneNumberFirstClick = false;
        }
    }//GEN-LAST:event_jTextFieldPhoneNumberMousePressed

    private void jTextFieldPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneNumberActionPerformed

    private void jTextFieldDNIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDNIMousePressed
        if (userDNIFirstClick) {
            jTextFieldDNI.setForeground(Color.black);
            userDNIFirstClick = false;
        }
    }//GEN-LAST:event_jTextFieldDNIMousePressed

    private void jTextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNIActionPerformed

    private void jTextFieldApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldApellidoMousePressed
        if (lastNameFirstClick) {
            jTextFieldApellido.setForeground(Color.black);
            lastNameFirstClick = false;
        }
    }//GEN-LAST:event_jTextFieldApellidoMousePressed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        int idUser;
        String nombre = jTextFieldNombre.getText();
        String apellido = jTextFieldApellido.getText();
        String dni = jTextFieldDNI.getText();
        String phoneNumber = jTextFieldPhoneNumber.getText();
        String email = jTextFieldEmail.getText();
        String password = jPasswordField.getText();
        String passwordRepeat = jPasswordField.getText();
        String role = (String) jComboBoxRole.getSelectedItem();
        
        
        // Expresiones regulares para validar
        String dniRegex = "^[0-9]{8}[A-Za-z]$"; // 8 dígitos seguidos de una letra
        String phoneRegex = "^[0-9]{9}$"; // Exactamente 9 dígitos
        String emailRegex = "^[A-Za-z0-9+_.-]+@(.+)$";
        
        // Validaciones
        if (nombre.trim().isEmpty() || apellido.trim().isEmpty() || dni.trim().isEmpty() ||
            phoneNumber.trim().isEmpty() || email.trim().isEmpty() || password.trim().isEmpty() || role == null) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!dni.matches(dniRegex)) {
            JOptionPane.showMessageDialog(this, "El DNI debe contener 8 números seguidos de una letra.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!phoneNumber.matches(phoneRegex)) {
            JOptionPane.showMessageDialog(this, "El número de teléfono debe contener exactamente 9 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!email.matches(emailRegex)) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un correo electrónico válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if (!password.equals(passwordRepeat)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        idUser=getUserIdByNameAndSurname(nombre, apellido);
        try {
            updateUser(idUser, nombre, apellido, username, dni, phoneNumber, email, password, role);
            System.out.println("Usuario actualizado exitosamente.");
        } catch (Exception e) {
            System.err.println("Error al actualizar el usuario: " + e.getMessage());
            e.printStackTrace(); // Imprime la pila de llamadas para depuración
        }
    }//GEN-LAST:event_reloadButtonActionPerformed

    private void jPasswordRepeatFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordRepeatFieldMousePressed
        if (passwordFieldRepeatFirstClick) {
            jPasswordRepeatField.setText("");
            jPasswordRepeatField.setForeground(Color.black);
            passwordFieldRepeatFirstClick = false;
        }
    }//GEN-LAST:event_jPasswordRepeatFieldMousePressed

    private void jPasswordRepeatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordRepeatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordRepeatFieldActionPerformed

    private void jComboBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoleActionPerformed

    private void jComboBoxRoleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxRoleMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoleMousePressed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonPanel;
    private javax.swing.JPanel BotonPanel1;
    private javax.swing.JButton Button;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel UserLabel1;
    private javax.swing.JLabel UserLabel2;
    private javax.swing.JLabel UserLabel3;
    private javax.swing.JLabel UserLabel4;
    private javax.swing.JLabel UserLabel5;
    private javax.swing.JLabel UserLabel6;
    private javax.swing.JLabel UserLabel7;
    private javax.swing.JComboBox<String> jComboBoxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jPasswordField;
    private javax.swing.JTextField jPasswordRepeatField;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JButton reloadButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String empresaSeleccionada, ImageIcon empresaLogo) {
        jLabel2.setForeground(Color.WHITE); // Aquí se cambia el color del texto a blanco
        jLabel2.setText(empresaSeleccionada);
        jLabel1.setIcon(empresaLogo);
    }
}
