/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gameclients;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author User
 */
public class Inicio extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form Login
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        // Suscribirse a GlobalState
        GlobalState.getInstance().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        BotonPanel = new javax.swing.JPanel();
        Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Logo2_BG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonPanel1 = new javax.swing.JPanel();
        Button1 = new javax.swing.JButton();
        BotonPanel2 = new javax.swing.JPanel();
        Button2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocationByPlatform(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(26, 41, 58));
        BG.setForeground(new java.awt.Color(23, 29, 39));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonPanel.setBackground(new java.awt.Color(92, 126, 16));
        BotonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Button.setBackground(new java.awt.Color(92, 126, 16));
        Button.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Button.setForeground(new java.awt.Color(255, 255, 255));
        Button.setText("REGISTER");
        Button.setBorder(null);
        Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMouseClicked(evt);
            }
        });
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanelLayout = new javax.swing.GroupLayout(BotonPanel);
        BotonPanel.setLayout(BotonPanelLayout);
        BotonPanelLayout.setHorizontalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanelLayout.setVerticalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(BotonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 120, 50));

        jPanel1.setBackground(new java.awt.Color(23, 29, 37));

        Logo2_BG.setBackground(new java.awt.Color(255, 255, 255));
        Logo2_BG.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Logo2_BG.setForeground(new java.awt.Color(0, 0, 0));
        Logo2_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/steam.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Logo2_BG)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo2_BG, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        BotonPanel1.setBackground(new java.awt.Color(92, 126, 16));
        BotonPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Button1.setBackground(new java.awt.Color(92, 126, 16));
        Button1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Button1.setForeground(new java.awt.Color(255, 255, 255));
        Button1.setText("LOGIN");
        Button1.setBorder(null);
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanel1Layout = new javax.swing.GroupLayout(BotonPanel1);
        BotonPanel1.setLayout(BotonPanel1Layout);
        BotonPanel1Layout.setHorizontalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanel1Layout.setVerticalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(BotonPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        BotonPanel2.setBackground(new java.awt.Color(92, 126, 16));
        BotonPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Button2.setBackground(new java.awt.Color(92, 126, 16));
        Button2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Button2.setForeground(new java.awt.Color(255, 255, 255));
        Button2.setText("SEE GAMES");
        Button2.setBorder(null);
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanel2Layout = new javax.swing.GroupLayout(BotonPanel2);
        BotonPanel2.setLayout(BotonPanel2Layout);
        BotonPanel2Layout.setHorizontalGroup(
            BotonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanel2Layout.setVerticalGroup(
            BotonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(BotonPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        Registro registro2 = new Registro();
        registro2.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
        registro2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        Login login3 = new Login();
        login3.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
        login3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        SeeGames steam2 = new SeeGames();
        steam2.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
        steam2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button2ActionPerformed

    private void ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonMouseClicked

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BotonPanel;
    private javax.swing.JPanel BotonPanel1;
    private javax.swing.JPanel BotonPanel2;
    private javax.swing.JButton Button;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JLabel Logo2_BG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String empresaSeleccionada, ImageIcon empresaLogo) {
        jLabel1.setForeground(Color.WHITE); // Aquí se cambia el color del texto a blanco
        jLabel1.setText(empresaSeleccionada);
        Logo2_BG.setIcon(empresaLogo);
    }
}
