/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gameclients;

import java.awt.Color;
import javax.swing.JOptionPane;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import java.sql.*;
import static db.User.getUserRoleByUsername;
import javax.swing.ImageIcon;



/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame implements Observer{

    // Declaración de las variables booleanas para indicar si los campos han sido clicados
    private boolean passwordFieldFirstClick = true;
    private boolean userFieldFirstClick = true;

    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        // Suscribirse a GlobalState
        GlobalState.getInstance().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        PasswordLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        PasswordField = new javax.swing.JPasswordField();
        BotonPanel = new javax.swing.JPanel();
        Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Logo2_BG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonPanel1 = new javax.swing.JPanel();
        Button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocationByPlatform(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(26, 41, 58));
        BG.setForeground(new java.awt.Color(23, 29, 39));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("LOGIN");
        BG.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 140, 30));

        UserLabel.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setText("USER: ");
        BG.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        UserField.setBackground(new java.awt.Color(255, 255, 255));
        UserField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        UserField.setForeground(new java.awt.Color(204, 204, 204));
        UserField.setText("Ingrese su nombre de usuario");
        UserField.setBorder(null);
        UserField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserFieldMousePressed(evt);
            }
        });
        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });
        BG.add(UserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 210, 30));
        BG.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 210, 30));

        PasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("PASSWORD: ");
        BG.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));
        BG.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 210, 30));

        PasswordField.setBackground(new java.awt.Color(255, 255, 255));
        PasswordField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(153, 153, 153));
        PasswordField.setText("00000000");
        PasswordField.setBorder(null);
        PasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordFieldMousePressed(evt);
            }
        });
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        BG.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 210, 30));

        BotonPanel.setBackground(new java.awt.Color(92, 126, 16));
        BotonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Button.setBackground(new java.awt.Color(92, 126, 16));
        Button.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Button.setForeground(new java.awt.Color(255, 255, 255));
        Button.setText("ENTER");
        Button.setBorder(null);
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanelLayout = new javax.swing.GroupLayout(BotonPanel);
        BotonPanel.setLayout(BotonPanelLayout);
        BotonPanelLayout.setHorizontalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanelLayout.setVerticalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(BotonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 120, 50));

        jPanel1.setBackground(new java.awt.Color(23, 29, 37));

        Logo2_BG.setBackground(new java.awt.Color(255, 255, 255));
        Logo2_BG.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Logo2_BG.setForeground(new java.awt.Color(0, 0, 0));
        Logo2_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/steam.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Logo2_BG)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(471, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo2_BG, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        BotonPanel1.setBackground(new java.awt.Color(23, 29, 37));
        BotonPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Button1.setBackground(new java.awt.Color(23, 29, 37));
        Button1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Button1.setForeground(new java.awt.Color(255, 255, 255));
        Button1.setText("GO BACK");
        Button1.setBorder(null);
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanel1Layout = new javax.swing.GroupLayout(BotonPanel1);
        BotonPanel1.setLayout(BotonPanel1Layout);
        BotonPanel1Layout.setHorizontalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanel1Layout.setVerticalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(BotonPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        String username = UserField.getText();
        String password = new String(PasswordField.getPassword());

        // Validar credenciales y obtener el rol
        
        String role = validateCredentials(username, password);

        if ("User".equals(role)) {
            JOptionPane.showMessageDialog(null, "Usuario inicio sesión correctamente", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
            LoggedMenu steam3 = new LoggedMenu(username, role);
            steam3.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
            steam3.setVisible(true);
            this.dispose();
        } else if("Admin".equals(role)){
            JOptionPane.showMessageDialog(null, "Administrador inicio sesión correctamente", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
            LoggedMenu steam3 = new LoggedMenu(username, role);
            steam3.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
            steam3.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonActionPerformed

    private String  validateCredentials(String username, String password) {
        String role = null;
        String query = "SELECT role FROM users WHERE username = ? AND password = ?";

        // Información de la base de datos
        String url = "jdbc:mysql://localhost:3306/juegos";
        String user = "root";
        String pass = "";

        try (Connection connection = DriverManager.getConnection(url, user, pass);
             PreparedStatement statement = connection.prepareStatement(query)) {
            
            statement.setString(1, username);
            statement.setString(2, password);

            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    role = resultSet.getString("role");
                }
            }
        } catch (SQLException e) {
            System.err.println("SQL Exception: " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("Exception: " + e.getMessage());
            e.printStackTrace();
        }

        return role;
    }

    
    private void PasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMousePressed
        // Si es la primera vez que se hace clic en el campo
        if (passwordFieldFirstClick) {
            PasswordField.setText("");  // Borra el texto
            PasswordField.setForeground(Color.black);  // Cambia el color del texto
            passwordFieldFirstClick = false;  // Cambia el estado a falso para que no se vuelva a ejecutar esta acción
        }
        // El campo funcionará normalmente después de la primera vez
    }//GEN-LAST:event_PasswordFieldMousePressed

    private void UserFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserFieldMousePressed
        // Si es la primera vez que se hace clic en el campo
        if (userFieldFirstClick) {
            UserField.setText("");  // Borra el texto
            UserField.setForeground(Color.black);  // Cambia el color del texto
            userFieldFirstClick = false;  // Cambia el estado a falso para que no se vuelva a ejecutar esta acción
        }
        // El campo funcionará normalmente después de la primera vez
    }//GEN-LAST:event_UserFieldMousePressed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        Inicio steam1 = new Inicio();
        steam1.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
        steam1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BotonPanel;
    private javax.swing.JPanel BotonPanel1;
    private javax.swing.JButton Button;
    private javax.swing.JButton Button1;
    private javax.swing.JLabel Logo2_BG;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField UserField;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String empresaSeleccionada, ImageIcon empresaLogo) {
        jLabel1.setForeground(Color.WHITE); // Aquí se cambia el color del texto a blanco
        jLabel1.setText(empresaSeleccionada);
        Logo2_BG.setIcon(empresaLogo);
    }
}
