/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gameclients;

import java.awt.Color;
import javax.swing.JOptionPane;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import static db.User.addUser;
import javax.swing.ImageIcon;


/**
 *
 * @author User
 */
public class Registro extends javax.swing.JFrame implements Observer{
    
    // Declaración de las variables booleanas para indicar si los campos han sido clicados
    private boolean passwordFieldFirstClick = true;
    private boolean nameFirstClick = true;
    private boolean userEmailFirstClick = true;
    private boolean lastNameFirstClick = true;
    private boolean userNameFirstClick = true;
    private boolean passwordFieldRepeatFirstClick = true;
    private boolean userDNIFirstClick = true;
    private boolean phoneNumberFirstClick = true;
    private boolean locationFirstClick = true;
    private boolean codigoTextFieldFirstClick = true;
    
    /**
     * Creates new form Login
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        // Suscribirse a GlobalState
        GlobalState.getInstance().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        BotonPanel = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Logo2_BG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        UserLabel1 = new javax.swing.JLabel();
        UserEmail = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        UserLabel2 = new javax.swing.JLabel();
        UserLabel3 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        UserLabel4 = new javax.swing.JLabel();
        PasswordFieldRepeat = new javax.swing.JPasswordField();
        UserLabel5 = new javax.swing.JLabel();
        UserDNI = new javax.swing.JTextField();
        UserLabel7 = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JTextField();
        BotonPanel1 = new javax.swing.JPanel();
        Button1 = new javax.swing.JButton();
        UserLabel6 = new javax.swing.JLabel();
        adminCheckBox = new javax.swing.JCheckBox();
        codigoTextField = new javax.swing.JTextField();
        Location = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocationByPlatform(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(26, 41, 58));
        BG.setForeground(new java.awt.Color(23, 29, 39));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("REGISTER");
        BG.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 140, 30));

        UserLabel.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setText("NAME: ");
        BG.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        Name.setBackground(new java.awt.Color(255, 255, 255));
        Name.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Name.setForeground(new java.awt.Color(204, 204, 204));
        Name.setText("Ingrese su nombre");
        Name.setBorder(null);
        Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NameMousePressed(evt);
            }
        });
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        BG.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 210, 30));

        PasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("REPEAT PASSWORD: ");
        BG.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        PasswordField.setBackground(new java.awt.Color(255, 255, 255));
        PasswordField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(153, 153, 153));
        PasswordField.setText("00000000");
        PasswordField.setBorder(null);
        PasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordFieldMousePressed(evt);
            }
        });
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        BG.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 210, 30));

        BotonPanel.setBackground(new java.awt.Color(92, 126, 16));
        BotonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        submitButton.setBackground(new java.awt.Color(92, 126, 16));
        submitButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("SUBMIT");
        submitButton.setBorder(null);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanelLayout = new javax.swing.GroupLayout(BotonPanel);
        BotonPanel.setLayout(BotonPanelLayout);
        BotonPanelLayout.setHorizontalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanelLayout.setVerticalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(BotonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 120, 50));

        jPanel1.setBackground(new java.awt.Color(23, 29, 37));

        Logo2_BG.setBackground(new java.awt.Color(255, 255, 255));
        Logo2_BG.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Logo2_BG.setForeground(new java.awt.Color(0, 0, 0));
        Logo2_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/steam.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Logo2_BG)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(459, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo2_BG, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        UserLabel1.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel1.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel1.setText("LOCATION: ");
        BG.add(UserLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        UserEmail.setBackground(new java.awt.Color(255, 255, 255));
        UserEmail.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        UserEmail.setForeground(new java.awt.Color(204, 204, 204));
        UserEmail.setText("Ingrese su email");
        UserEmail.setBorder(null);
        UserEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserEmailMousePressed(evt);
            }
        });
        UserEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserEmailActionPerformed(evt);
            }
        });
        BG.add(UserEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 210, 30));

        LastName.setBackground(new java.awt.Color(255, 255, 255));
        LastName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        LastName.setForeground(new java.awt.Color(204, 204, 204));
        LastName.setText(" Ingrese sus apellidos");
        LastName.setBorder(null);
        LastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LastNameMousePressed(evt);
            }
        });
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });
        BG.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 210, 30));

        UserLabel2.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel2.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel2.setText("LAST NAME: ");
        BG.add(UserLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        UserLabel3.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel3.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel3.setText("USER NAME: ");
        BG.add(UserLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        UserName.setBackground(new java.awt.Color(255, 255, 255));
        UserName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        UserName.setForeground(new java.awt.Color(204, 204, 204));
        UserName.setText(" Ingrese su nombre de usuario");
        UserName.setBorder(null);
        UserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserNameMousePressed(evt);
            }
        });
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        BG.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 210, 30));

        UserLabel4.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel4.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel4.setText("PASSWORD: ");
        BG.add(UserLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        PasswordFieldRepeat.setBackground(new java.awt.Color(255, 255, 255));
        PasswordFieldRepeat.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        PasswordFieldRepeat.setForeground(new java.awt.Color(153, 153, 153));
        PasswordFieldRepeat.setText("00000000");
        PasswordFieldRepeat.setBorder(null);
        PasswordFieldRepeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordFieldRepeatMousePressed(evt);
            }
        });
        PasswordFieldRepeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldRepeatActionPerformed(evt);
            }
        });
        BG.add(PasswordFieldRepeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 210, 30));

        UserLabel5.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel5.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel5.setText("DNI: ");
        BG.add(UserLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        UserDNI.setBackground(new java.awt.Color(255, 255, 255));
        UserDNI.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        UserDNI.setForeground(new java.awt.Color(204, 204, 204));
        UserDNI.setText(" Ingrese su DNI");
        UserDNI.setBorder(null);
        UserDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserDNIMousePressed(evt);
            }
        });
        UserDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserDNIActionPerformed(evt);
            }
        });
        BG.add(UserDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 210, 30));

        UserLabel7.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel7.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel7.setText("PHONE NUMBER: ");
        BG.add(UserLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 190, -1));

        PhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        PhoneNumber.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        PhoneNumber.setForeground(new java.awt.Color(204, 204, 204));
        PhoneNumber.setText(" Ingrese su numero de telefono");
        PhoneNumber.setBorder(null);
        PhoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PhoneNumberMousePressed(evt);
            }
        });
        PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberActionPerformed(evt);
            }
        });
        BG.add(PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 210, 30));

        BotonPanel1.setBackground(new java.awt.Color(23, 29, 37));
        BotonPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Button1.setBackground(new java.awt.Color(23, 29, 37));
        Button1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Button1.setForeground(new java.awt.Color(255, 255, 255));
        Button1.setText("GO BACK");
        Button1.setBorder(null);
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonPanel1Layout = new javax.swing.GroupLayout(BotonPanel1);
        BotonPanel1.setLayout(BotonPanel1Layout);
        BotonPanel1Layout.setHorizontalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonPanel1Layout.setVerticalGroup(
            BotonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(BotonPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 120, 50));

        UserLabel6.setBackground(new java.awt.Color(255, 255, 255));
        UserLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UserLabel6.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel6.setText("EMAIL: ");
        BG.add(UserLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        adminCheckBox.setBackground(new java.awt.Color(222, 222, 222));
        adminCheckBox.setForeground(new java.awt.Color(153, 153, 153));
        adminCheckBox.setText("Admin");
        adminCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCheckBoxActionPerformed(evt);
            }
        });
        BG.add(adminCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 70, 30));

        codigoTextField.setBackground(new java.awt.Color(255, 255, 255));
        codigoTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        codigoTextField.setForeground(new java.awt.Color(204, 204, 204));
        codigoTextField.setText("Ingrese el codigo");
        codigoTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                codigoTextFieldMousePressed(evt);
            }
        });
        codigoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextFieldActionPerformed(evt);
            }
        });
        BG.add(codigoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 130, 30));

        Location.setBackground(new java.awt.Color(255, 255, 255));
        Location.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Location.setForeground(new java.awt.Color(204, 204, 204));
        Location.setText(" Ingrese el nombre de su localidad");
        Location.setBorder(null);
        Location.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LocationMousePressed(evt);
            }
        });
        Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationActionPerformed(evt);
            }
        });
        BG.add(Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed

    }//GEN-LAST:event_NameActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed

    }//GEN-LAST:event_PasswordFieldActionPerformed
    
    
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        validateAndSubmit();
    }//GEN-LAST:event_submitButtonActionPerformed
    
    private void validateAndSubmit() {
        String nombre = Name.getText();
        String apellido = LastName.getText();
        String usuario = UserName.getText();
        String dni = UserDNI.getText();
        String password = new String(PasswordField.getPassword());
        String passwordRepeat = new String(PasswordFieldRepeat.getPassword());
        String phoneNumber = PhoneNumber.getText();
        String email = UserEmail.getText();
        String codigo = codigoTextField.getText();

        // Expresiones regulares para validar
        String dniRegex = "^[0-9]{8}[A-Za-z]$"; // 8 dígitos seguidos de una letra
        String phoneRegex = "^[0-9]{9}$"; // Exactamente 9 dígitos
        String emailRegex = "^[A-Za-z0-9+_.-]+@(.+)$";

        // Validaciones
        if (nombre.trim().isEmpty() || nombre.equals("Ingrese su nombre") ||
            apellido.trim().isEmpty() || apellido.equals("Ingrese su apellido") ||
            usuario.trim().isEmpty() || usuario.equals("Ingrese su nombre de usuario") ||
            dni.trim().isEmpty() || dni.equals("Ingrese su DNI") ||
            email.trim().isEmpty() || email.equals("Ingrese su email") ||
            password.trim().isEmpty() || passwordRepeat.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!dni.matches(dniRegex)) {
            JOptionPane.showMessageDialog(null, "El DNI debe contener 8 números seguidos de una letra.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!phoneNumber.matches(phoneRegex)) {
            JOptionPane.showMessageDialog(null, "El número de teléfono debe contener exactamente 9 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!password.equals(passwordRepeat)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!email.matches(emailRegex)) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un correo electrónico válido.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Aquí llamamos al método para agregar el usuario a la base de datos
            // Verificar el checkbox y el código
        boolean isAdmin = adminCheckBox.isSelected();
        if (isAdmin && codigo.equals("1234")) {
            // Registrar como Administrador
            String role = "Admin";
            addUser(nombre, apellido, usuario, dni, phoneNumber, email, password, role);
        } else if (!isAdmin) {
            // Registrar como Usuario
            String role = "User";
            addUser(nombre, apellido, usuario, dni, phoneNumber, email, password, role);
        } else {
            JOptionPane.showMessageDialog(null, "Código de administrador incorrecto.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            // Confirmación de éxito
            JOptionPane.showMessageDialog(null, "Usuario añadido correctamente.", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);

            // Opcional: Mostrar nueva ventana y cerrar la actual
            Inicio steam1 = new Inicio();
            steam1.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
            steam1.setVisible(true);
            this.dispose();
        }
    }

    private void PasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMousePressed
            if (passwordFieldFirstClick) {
            PasswordField.setText("");
            PasswordField.setForeground(Color.black);
            passwordFieldFirstClick = false;
        }
    }//GEN-LAST:event_PasswordFieldMousePressed

    private void NameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameMousePressed
        if (nameFirstClick) {
            if (Name.getText().equals("Ingrese su nombre")) {
                Name.setText("");
                Name.setForeground(Color.black);
            }
            nameFirstClick = false;
        }
    }//GEN-LAST:event_NameMousePressed


    private void UserEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserEmailMousePressed
            if (userEmailFirstClick) {
            UserEmail.setText("");
            UserEmail.setForeground(Color.black);
            userEmailFirstClick = false;
        }
    }//GEN-LAST:event_UserEmailMousePressed

    private void UserEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserEmailActionPerformed

    }//GEN-LAST:event_UserEmailActionPerformed

    private void LastNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastNameMousePressed
            if (lastNameFirstClick) {
            LastName.setText("");
            LastName.setForeground(Color.black);
            lastNameFirstClick = false;
        }
    }//GEN-LAST:event_LastNameMousePressed

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void UserNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserNameMousePressed
            if (userNameFirstClick) {
            UserName.setText("");
            UserName.setForeground(Color.black);
            userNameFirstClick = false;
        }
    }//GEN-LAST:event_UserNameMousePressed

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed

    }//GEN-LAST:event_UserNameActionPerformed

    private void PasswordFieldRepeatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldRepeatMousePressed
            if (passwordFieldRepeatFirstClick) {
            PasswordFieldRepeat.setText("");
            PasswordFieldRepeat.setForeground(Color.black);
            passwordFieldRepeatFirstClick = false;
        }
    }//GEN-LAST:event_PasswordFieldRepeatMousePressed

    private void PasswordFieldRepeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldRepeatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldRepeatActionPerformed

    private void UserDNIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserDNIMousePressed
            if (userDNIFirstClick) {
            UserDNI.setText("");
            UserDNI.setForeground(Color.black);
            userDNIFirstClick = false;
        }
    }//GEN-LAST:event_UserDNIMousePressed

    private void UserDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserDNIActionPerformed

    }//GEN-LAST:event_UserDNIActionPerformed

    private void PhoneNumberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhoneNumberMousePressed
            if (phoneNumberFirstClick) {
            PhoneNumber.setText("");
            PhoneNumber.setForeground(Color.black);
            phoneNumberFirstClick = false;
        }
    }//GEN-LAST:event_PhoneNumberMousePressed

    private void PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberActionPerformed

    }//GEN-LAST:event_PhoneNumberActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        Inicio steam1 = new Inicio();
        steam1.update(GlobalState.getInstance().getEmpresaSeleccionada(), GlobalState.getInstance().getEmpresaLogo());
        steam1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button1ActionPerformed

    private void adminCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCheckBoxActionPerformed
        
    }//GEN-LAST:event_adminCheckBoxActionPerformed

    private void LocationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationMousePressed
            if (locationFirstClick) {
            Location.setText("");
            Location.setForeground(Color.black);
            locationFirstClick = false;
        }
    }//GEN-LAST:event_LocationMousePressed

    private void LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationActionPerformed

    }//GEN-LAST:event_LocationActionPerformed

    private void codigoTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoTextFieldMousePressed
            if (codigoTextFieldFirstClick) {
            codigoTextField.setText("");
            codigoTextField.setForeground(Color.black);
            codigoTextFieldFirstClick = false;
        }
    }//GEN-LAST:event_codigoTextFieldMousePressed

    private void codigoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextFieldActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BotonPanel;
    private javax.swing.JPanel BotonPanel1;
    private javax.swing.JButton Button1;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField Location;
    private javax.swing.JLabel Logo2_BG;
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPasswordField PasswordFieldRepeat;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField UserDNI;
    private javax.swing.JTextField UserEmail;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel UserLabel1;
    private javax.swing.JLabel UserLabel2;
    private javax.swing.JLabel UserLabel3;
    private javax.swing.JLabel UserLabel4;
    private javax.swing.JLabel UserLabel5;
    private javax.swing.JLabel UserLabel6;
    private javax.swing.JLabel UserLabel7;
    private javax.swing.JTextField UserName;
    private javax.swing.JCheckBox adminCheckBox;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String empresaSeleccionada, ImageIcon empresaLogo) {
        jLabel1.setForeground(Color.WHITE); // Aquí se cambia el color del texto a blanco
        jLabel1.setText(empresaSeleccionada);
        Logo2_BG.setIcon(empresaLogo);
    }
}
